Repository abhinavsingh/proxy.py, pull requests merged in 2019-10, with the labels that each got.

#106 Use selectors.DefaultSelector instead of select.select
  .github/workflows/testing.yml
  .travis.yml
  Makefile
  README.md
  fluentd.conf
  plugin_examples.py
  proxy.py
  setup.py
  tests.py
Labels: Bug Fix, Enhancement

#111 ssl.SSLError during handshake can teardown worker process
  proxy.py
Labels: Bug Fix

#109 Chrome Devtool Integration first steps
  .gitignore
  Makefile
  README.md
  package-lock.json
  package.json
  plugin_examples.py
  proxy.js
  proxy.py
  public/devtools/.gitkeep
  requirements-testing.txt
  tests.py
Labels: Enhancement

#121 Ensure explicit flush before upgrade while TLS intercepting
  .dockerignore
  .github/workflows/testing.yml
  Dockerfile
  Makefile
  README.md
  proxy.py
  requirements.txt
  setup.py
  tests.py
Labels: Bug Fix

#125 Invoke HttpWebServerBasePlugin.handle_request for each request in HTTP/1.1 pipeline
  README.md
  plugin_examples.py
  proxy.py
  tests.py
Labels: Enhancement

#128 Invoke proxy plugin handle_request for each request in HTTP/1.1 pipeline or when TLS interception is enabled
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  plugin_examples.py
  proxy.py
  tests.py
Labels: Bug Fix

#134 Threadless execution using coroutines
  .github/workflows/testing.yml
  .gitignore
  Makefile
  README.md
  benchmark.py
  chrome_with_proxy.sh
  monitor_open_files.sh
  plugin_examples.py
  proxy.py
  tests.py
Labels: Enhancement
